### ISSUE TITLE
Not able see my own hiring post

### ISSUE THREAD

**Issue by SujoyKrHaldar** [kanchana404/Fit-For-Hire#44]
After successfully creating a Job Hiring Post I cannot find that post in **/jobs** section. It is not visible at all.

**Comment by kanchana404** [comment]
Yeah it should aprove by manual by admin. Then you can see it.


Simply go to the /applicants


Then you can see your application status. Ill add a option to see that in tha dashboard asap ❤

**Comment by SujoyKrHaldar** [comment]
Thank you for the clarification. 
BTW very good project. 
Done upvoting in JSM hackathon.
